/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["health_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["health_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["auth_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Canjea la cookie de refresh por un access token nuevo y rota la cookie.
         */
        post: operations["auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["auth_get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change My Password */
        patch: operations["auth_change_my_password"];
        trace?: never;
    };
    "/auth/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Avatar */
        patch: operations["auth_update_avatar"];
        trace?: never;
    };
    "/players/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Players
         * @description Jugadores del usuario autenticado.
         */
        get: operations["players_list_players"];
        put?: never;
        /**
         * Add Player
         * @description Crea un jugador validándolo contra la Riot API. 404 si no existe en Riot.
         */
        post: operations["players_add_player"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player */
        get: operations["players_get_player"];
        /**
         * Edit Player
         * @description Actualiza los campos editables de un jugador (rol, apodo, notas).
         */
        put: operations["players_edit_player"];
        post?: never;
        /**
         * Remove Player
         * @description Elimina un jugador y sus snapshots.
         */
        delete: operations["players_remove_player"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player Summary
         * @description Rendimiento por rol sobre todas las partidas guardadas del jugador.
         */
        get: operations["players_get_player_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Player
         * @description Refresca el rango e icono del jugador consultando la Riot API.
         */
        post: operations["players_refresh_player"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/player/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Live Matches
         * @description Últimas N partidas del jugador (caché de 1 h), sin filtro de rol ni dependencia de snapshots.
         */
        get: operations["matches_list_live_matches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/snapshot/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Matches
         * @description Partidas de un snapshot, de la más reciente a la más antigua (solo BD).
         */
        get: operations["matches_list_matches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/snapshot/{snapshot_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Estadísticas agregadas de un snapshot, calculadas en SQL (queries/snapshot_summary.sql).
         */
        get: operations["matches_get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/player/{player_id}/most-played": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Most Played Champions
         * @description Top 3 campeones en las últimas partidas del jugador (desde el historial en BD).
         */
        get: operations["matches_get_most_played_champions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/player/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Snapshots
         * @description Snapshots de un jugador, del más reciente al más antiguo.
         */
        get: operations["snapshots_list_snapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Snapshot
         * @description Encola el análisis de un período y devuelve su job.
         *
         *     Idempotente: si ya hay un análisis en marcha del mismo jugador y rango, se
         *     devuelve ese job en lugar de lanzar otro. El progreso se sigue por SSE en
         *     GET /snapshots/jobs/{job_id}/stream.
         */
        post: operations["snapshots_create_snapshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Status */
        get: operations["snapshots_get_job_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Job
         * @description Progreso en tiempo real por Server-Sent Events.
         *
         *     SSE y no WebSockets: el flujo es unidireccional, funciona sobre HTTP normal
         *     y el navegador se reconecta solo. Al conectar (o reconectar) se envía
         *     primero el estado actual.
         */
        get: operations["snapshots_stream_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Job
         * @description Vuelve a encolar un análisis fallido (por ejemplo, uno interrumpido).
         */
        post: operations["snapshots_retry_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Snapshot */
        get: operations["snapshots_get_snapshot"];
        put?: never;
        post?: never;
        /**
         * Remove Snapshot
         * @description Elimina un snapshot; las partidas se conservan para otros snapshots.
         */
        delete: operations["snapshots_remove_snapshot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots/{snapshot_id}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Description */
        patch: operations["snapshots_edit_description"];
        trace?: never;
    };
    "/snapshots/{snapshot_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Notes */
        patch: operations["snapshots_edit_notes"];
        trace?: never;
    };
    "/snapshots/{snapshot_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Snapshot Dashboard
         * @description Dashboard del snapshot (cacheado). `compare_*` superpone en vivo el radar de otra cuenta.
         */
        get: operations["snapshots_read_snapshot_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["ddragon_get_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Items */
        get: operations["ddragon_get_items"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["ddragon_get_item"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/items/{item_id}/icon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item Icon */
        get: operations["ddragon_get_item_icon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/spells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spells */
        get: operations["ddragon_get_spells"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/spells/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spell */
        get: operations["ddragon_get_spell"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/runes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Runes */
        get: operations["ddragon_get_runes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/runes/{rune_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rune */
        get: operations["ddragon_get_rune"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/runes/{rune_id}/icon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rune Icon */
        get: operations["ddragon_get_rune_icon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Map
         * @description Redirige a la imagen del minimapa (map11.png) en el CDN de Riot.
         */
        get: operations["ddragon_get_map"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ddragon/map/url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Map Url */
        get: operations["ddragon_get_map_url"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/league/cutoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Rank Cutoffs
         * @description Grandmaster and Challenger LP cutoffs for a platform (cached for 4 hours).
         *
         *     - Grandmaster cutoff: LP of the player at overall rank 1000 (last GM slot).
         *     - Challenger cutoff: LP of the player at overall rank 300 (last Challenger slot).
         */
        get: operations["league_read_rank_cutoffs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/players/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Players */
        get: operations["admin_list_all_players"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin Delete Player */
        delete: operations["admin_admin_delete_player"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Global Stats */
        get: operations["admin_get_global_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["admin_list_users"];
        put?: never;
        /** Create User */
        post: operations["admin_create_user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User Role */
        patch: operations["admin_update_user_role"];
        trace?: never;
    };
    "/admin/users/{user_id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle User Active */
        patch: operations["admin_toggle_user_active"];
        trace?: never;
    };
    "/admin/users/inactive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Inactive Users */
        delete: operations["admin_delete_inactive_users"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["admin_delete_user"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["health_root"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminPlayerOut */
        AdminPlayerOut: {
            /** Id */
            id: number;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Region */
            region: string;
            /** Nickname */
            nickname: string;
            /** Role */
            role: string;
            /** Tier */
            tier: string;
            /** Rank */
            rank: string;
            /** Lp */
            lp: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Owner Username */
            owner_username: string;
        };
        /** Body_auth_update_avatar */
        Body_auth_update_avatar: {
            /** File */
            file: string;
        };
        /** ChampionStatsResponse */
        ChampionStatsResponse: {
            /** Champion Name */
            champion_name: string;
            /** Games Played */
            games_played: number;
            /** Win Rate */
            win_rate: number;
            /** Icon Url */
            icon_url: string;
        };
        /**
         * ChangePasswordRequest
         * @description Datos para cambiar la contraseña del usuario autenticado.
         */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** DeathsByPhase */
        DeathsByPhase: {
            /** Early Deaths */
            early_deaths: number;
            /** Mid Deaths */
            mid_deaths: number;
            /** Late Deaths */
            late_deaths: number;
        };
        /** DeleteInactiveResult */
        DeleteInactiveResult: {
            /** Deleted */
            deleted: number;
        };
        /** GlobalStats */
        GlobalStats: {
            /** Total Users */
            total_users: number;
            /** Active Users */
            active_users: number;
            /** Inactive Users */
            inactive_users: number;
            /** Total Players */
            total_players: number;
            /** Total Snapshots */
            total_snapshots: number;
            /** Total Matches */
            total_matches: number;
            /** Tier Distribution */
            tier_distribution: components["schemas"]["TierCount"][];
            /** Region Distribution */
            region_distribution: components["schemas"]["RegionCount"][];
            /** Top Users */
            top_users: components["schemas"]["TopUser"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Checks */
            checks: {
                [key: string]: "ok" | "error";
            };
        };
        /** MatchResponse */
        MatchResponse: {
            /** Match Id */
            match_id: string;
            /** Player Id */
            player_id?: number | null;
            /** Snapshot Id */
            snapshot_id?: number | null;
            /**
             * Creation Time
             * Format: date-time
             */
            creation_time: string;
            /** Champion */
            champion: string;
            /** Win */
            win: boolean;
            /** Duration */
            duration: number;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Kill Participation */
            kill_participation: number;
            /** Vision */
            vision: number;
            /** Damage */
            damage: number;
            /** Gold */
            gold: number;
            /** Total Cs */
            total_cs: number;
            /** Damage Share */
            damage_share: number;
            /** First Dragon */
            first_dragon: boolean;
            /** Void Grubs */
            void_grubs: boolean;
            /** Herald */
            herald: boolean;
            /**
             * Summoner1 Id
             * @default 0
             */
            summoner1_id: number;
            /**
             * Summoner2 Id
             * @default 0
             */
            summoner2_id: number;
            /**
             * Item0
             * @default 0
             */
            item0: number;
            /**
             * Item1
             * @default 0
             */
            item1: number;
            /**
             * Item2
             * @default 0
             */
            item2: number;
            /**
             * Item3
             * @default 0
             */
            item3: number;
            /**
             * Item4
             * @default 0
             */
            item4: number;
            /**
             * Item5
             * @default 0
             */
            item5: number;
            /**
             * Item6
             * @default 0
             */
            item6: number;
            /**
             * Primary Rune
             * @default 0
             */
            primary_rune: number;
            /**
             * Secondary Tree
             * @default 0
             */
            secondary_tree: number;
            /**
             * Death Events
             * @default []
             */
            death_events: unknown[] | null;
            /**
             * Ward Events
             * @default []
             */
            ward_events: unknown[] | null;
            /**
             * Dragon Setups
             * @default []
             */
            dragon_setups: unknown[] | null;
            /** Solo Kills */
            solo_kills?: number | null;
            /**
             * Damage Structures
             * @default 0
             */
            damage_structures: number;
            /**
             * Gold Share
             * @default 0
             */
            gold_share: number;
            /**
             * Enemy Jg Monsters
             * @default 0
             */
            enemy_jg_monsters: number;
            /**
             * Control Wards
             * @default 0
             */
            control_wards: number;
            /** Roaming Proactivity */
            roaming_proactivity?: number | null;
            /** Objective Vision Score */
            objective_vision_score?: number | null;
            /**
             * Early Gank Deaths
             * @default 0
             */
            early_gank_deaths: number | null;
            /** Player Role */
            player_role?: string | null;
            /**
             * Role Bound Item
             * @default 0
             */
            role_bound_item: number | null;
            /**
             * Quest Completed
             * @default false
             */
            quest_completed: boolean | null;
            /** Quest Completion Time */
            quest_completion_time?: number | null;
            /** Enemy Quest Completion Time */
            enemy_quest_completion_time?: number | null;
            /** Quest Completion Time Diff */
            quest_completion_time_diff?: number | null;
            /** Fullclear Time */
            fullclear_time?: number | null;
            /** Cs 8 */
            cs_8?: number | null;
            /** Cs 14 */
            cs_14?: number | null;
            /** Cs 25 */
            cs_25?: number | null;
            /** Cs Diff 8 */
            cs_diff_8?: number | null;
            /** Cs Diff 14 */
            cs_diff_14?: number | null;
            /** Cs Diff 25 */
            cs_diff_25?: number | null;
            /** Gold Diff 8 */
            gold_diff_8?: number | null;
            /** Gold Diff 14 */
            gold_diff_14?: number | null;
            /** Gold Diff 25 */
            gold_diff_25?: number | null;
            /** Xp Diff 8 */
            xp_diff_8?: number | null;
            /** Xp Diff 14 */
            xp_diff_14?: number | null;
            /** Xp Diff 25 */
            xp_diff_25?: number | null;
            /** Quest Item Id */
            readonly quest_item_id: number;
            /** Duration Minutes */
            readonly duration_minutes: number;
            /** Kda */
            readonly kda: number;
            /** Cs Per Min */
            readonly cs_per_min: number;
            /** Dmg Per Min */
            readonly dmg_per_min: number;
            /** Gold Per Min */
            readonly gold_per_min: number;
            /** Fullclear Timer */
            readonly fullclear_timer: string | null;
            /** Vision Per Min */
            readonly vision_per_min: number;
            /** Deaths By Phase */
            readonly deaths_by_phase: {
                [key: string]: number;
            };
            /** Death Events Normalized */
            readonly death_events_normalized: {
                [key: string]: unknown;
            }[];
            /** Ward Events Normalized */
            readonly ward_events_normalized: {
                [key: string]: unknown;
            }[];
            /** Dragon Setups Summary */
            readonly dragon_setups_summary: {
                [key: string]: unknown;
            };
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
            /** Status */
            status: string;
        };
        /** MostPlayedChampionResponse */
        MostPlayedChampionResponse: {
            /** Champion Name */
            champion_name: string;
            /** Games Played */
            games_played: number;
            /** Win Rate */
            win_rate: number;
            /** Icon Url */
            icon_url: string;
        };
        /** Page[AdminPlayerOut] */
        Page_AdminPlayerOut_: {
            /** Items */
            items: components["schemas"]["AdminPlayerOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[MatchResponse] */
        Page_MatchResponse_: {
            /** Items */
            items: components["schemas"]["MatchResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[PlayerResponse] */
        Page_PlayerResponse_: {
            /** Items */
            items: components["schemas"]["PlayerResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SnapshotResponse] */
        Page_SnapshotResponse_: {
            /** Items */
            items: components["schemas"]["SnapshotResponse"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[UserOut] */
        Page_UserOut_: {
            /** Items */
            items: components["schemas"]["UserOut"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * PlayerCreate
         * @description Lo que recibe la API al crear un jugador. Sin puuid ni id — los genera el sistema.
         */
        PlayerCreate: {
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Region */
            region: string;
            /**
             * Nickname
             * @default
             */
            nickname: string | null;
            /** @default ALL */
            role: components["schemas"]["Role"];
            /**
             * Notes
             * @default
             */
            notes: string | null;
        };
        /**
         * PlayerResponse
         * @description Lo que devuelve la API. Incluye id, puuid, datos de rango e icono.
         */
        PlayerResponse: {
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Region */
            region: string;
            /**
             * Nickname
             * @default
             */
            nickname: string | null;
            /** @default ALL */
            role: components["schemas"]["Role"];
            /**
             * Notes
             * @default
             */
            notes: string | null;
            /** Id */
            id: number;
            /** Puuid */
            puuid: string;
            /**
             * Tier
             * @default
             */
            tier: string | null;
            /**
             * Rank
             * @default
             */
            rank: string | null;
            /**
             * Lp
             * @default 0
             */
            lp: number | null;
            /**
             * Profile Icon Id
             * @default 0
             */
            profile_icon_id: number | null;
            /**
             * Wins
             * @default 0
             */
            wins: number | null;
            /**
             * Losses
             * @default 0
             */
            losses: number | null;
            /**
             * Win Rate
             * @default 0
             */
            win_rate: number;
        };
        /**
         * PlayerUpdate
         * @description Campos actualizables desde la UI.
         */
        PlayerUpdate: {
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            role: components["schemas"]["Role"];
            /**
             * Nickname
             * @default
             */
            nickname: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** RadarChartData */
        RadarChartData: {
            /** Axes */
            axes: string[];
            player_dataset: components["schemas"]["RadarDataset"];
            /** Rank Datasets */
            rank_datasets: {
                [key: string]: components["schemas"]["RadarDataset"];
            };
            /** Pro Datasets */
            pro_datasets: {
                [key: string]: components["schemas"]["RadarDataset"];
            };
        };
        /** RadarDataset */
        RadarDataset: {
            /** Label */
            label: string;
            /** Values */
            values: {
                [key: string]: number;
            };
            /** Normalized Values */
            normalized_values: {
                [key: string]: number;
            };
        };
        /** RankCutoffsResponse */
        RankCutoffsResponse: {
            /** Region */
            region: string;
            /** Platform */
            platform: string;
            /** Grandmaster Cutoff Lp */
            grandmaster_cutoff_lp: number;
            /** Challenger Cutoff Lp */
            challenger_cutoff_lp: number;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /** RegionCount */
        RegionCount: {
            /** Region */
            region: string;
            /** Count */
            count: number;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "TOP" | "JUNGLE" | "MID" | "BOTTOM" | "SUPPORT" | "ALL";
        /** RoleAverageMetric */
        RoleAverageMetric: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /** Status */
            status: string;
            /** Threshold */
            threshold: number;
            /**
             * Unit
             * @default
             */
            unit: string;
        };
        /**
         * RoleSummary
         * @description Rendimiento agregado de un jugador en un rol (consulta SQL player_role_summary).
         */
        RoleSummary: {
            /** Role */
            role: string;
            /** Games */
            games: number;
            /** Win Rate */
            win_rate: number;
            /** Kda */
            kda: number;
            /** Cs Per Min */
            cs_per_min: number;
            /** Gold Diff 14 */
            gold_diff_14: number | null;
            /** Deaths */
            deaths: number;
        };
        /** RoleUpdate */
        RoleUpdate: {
            /** Role */
            role: string;
        };
        /**
         * SnapshotCreate
         * @description Lo que recibe la API al lanzar un análisis.
         */
        SnapshotCreate: {
            /** Player Id */
            player_id: number;
            /** Date From */
            date_from: number;
            /** Date To */
            date_to: number;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * SnapshotDashboardResponse
         * @description Dashboard de un snapshot.
         *
         *     No incluye la lista de partidas (P9): se piden paginadas en
         *     GET /matches/snapshot/{snapshot_id}. Así la respuesta cabe en caché y no
         *     crece con el número de partidas.
         */
        SnapshotDashboardResponse: {
            /** Snapshot Id */
            snapshot_id: number;
            /** Player Id */
            player_id: number;
            /** Player Name */
            player_name: string;
            /**
             * Date From
             * Format: date-time
             */
            date_from: string;
            /**
             * Date To
             * Format: date-time
             */
            date_to: string;
            /**
             * Description
             * @default
             */
            description: string | null;
            /**
             * Notes
             * @default
             */
            notes: string | null;
            /** Active Role */
            active_role: string;
            /** Games Played */
            games_played: number;
            /** Role Averages */
            role_averages: components["schemas"]["RoleAverageMetric"][];
            /** Played Champions */
            played_champions: components["schemas"]["ChampionStatsResponse"][];
            deaths_by_phase: components["schemas"]["DeathsByPhase"];
            /** Performance Trends */
            performance_trends: components["schemas"]["TrendPoint"][];
            radar_data: components["schemas"]["RadarChartData"];
        };
        /**
         * SnapshotDescriptionUpdate
         * @description Para editar la descripción de un snapshot.
         */
        SnapshotDescriptionUpdate: {
            /** Description */
            description: string;
        };
        /**
         * SnapshotJobResponse
         * @description Respuesta al lanzar un análisis. Si ya había uno igual en marcha, es ese mismo job.
         */
        SnapshotJobResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "processing" | "done" | "error";
        };
        /**
         * SnapshotJobStatus
         * @description Estado de un análisis. Mismo formato en GET /jobs/{id} y en los eventos SSE.
         */
        SnapshotJobStatus: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "done" | "error";
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /** Snapshot Id */
            snapshot_id?: number | null;
            /** Error */
            error?: string | null;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
        };
        /**
         * SnapshotNotesUpdate
         * @description Para editar las notas inline desde la UI.
         */
        SnapshotNotesUpdate: {
            /** Notes */
            notes: string;
        };
        /**
         * SnapshotResponse
         * @description Lo que devuelve la API al listar snapshots.
         */
        SnapshotResponse: {
            /** Id */
            id: number;
            /** Player Id */
            player_id: number;
            /**
             * Date From
             * Format: date-time
             */
            date_from: string;
            /**
             * Date To
             * Format: date-time
             */
            date_to: string;
            /**
             * Description
             * @default
             */
            description: string | null;
            /**
             * Notes
             * @default
             */
            notes: string | null;
            /**
             * Match Count
             * @default 0
             */
            match_count: number;
        };
        /** SnapshotStatsResponse */
        SnapshotStatsResponse: {
            /** Snapshot Id */
            snapshot_id: number;
            /** Games Played */
            games_played: number;
            /** Winrate */
            winrate: number;
            /** Avg Kda */
            avg_kda: number;
            /** Avg Cs Per Min */
            avg_cs_per_min: number;
            /** Avg Damage Per Min */
            avg_damage_per_min: number;
            /** Avg Gold Per Min */
            avg_gold_per_min: number;
            /** Avg Vision */
            avg_vision: number;
            /** Avg Kill Participation */
            avg_kill_participation: number;
            /** First Dragon Rate */
            first_dragon_rate: string;
            /** Herald Rate */
            herald_rate: string;
            /** Two Or More Void Grubs Rate */
            two_or_more_void_grubs_rate: string;
        };
        /** TierCount */
        TierCount: {
            /** Tier */
            tier: string;
            /** Count */
            count: number;
        };
        /**
         * TokenResponse
         * @description Access token de vida corta. El refresh token viaja aparte, en una cookie httpOnly.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** TopUser */
        TopUser: {
            /** Username */
            username: string;
            /** Player Count */
            player_count: number;
        };
        /** TrendPoint */
        TrendPoint: {
            /** Game Num */
            game_num: number;
            /** Match Id */
            match_id: string;
            /**
             * Creation Time
             * Format: date-time
             */
            creation_time: string;
            /** Champion */
            champion: string;
            /** Win */
            win: boolean;
            /** Kda */
            kda: number;
            /** Cs Per Min */
            cs_per_min: number;
            /** Gold Per Min */
            gold_per_min: number;
            /** Vision Per Min */
            vision_per_min: number;
            /** Kda Moving Avg */
            kda_moving_avg: number;
            /** Cs Moving Avg */
            cs_moving_avg: number;
            /** Gold Moving Avg */
            gold_moving_avg: number;
            /** Vision Moving Avg */
            vision_moving_avg: number;
        };
        /** UrlResponse */
        UrlResponse: {
            /** Url */
            url: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default user
             */
            role: string;
        };
        /**
         * UserLogin
         * @description Credenciales para iniciar sesión (sin política: las cuentas antiguas deben poder entrar).
         */
        UserLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * UserRegister
         * @description Datos necesarios para registrar un nuevo usuario.
         */
        UserRegister: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * UserResponse
         * @description Datos públicos del usuario autenticado.
         */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Username */
            username: string;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A dependency is down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    auth_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Missing, expired, revoked or reused refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    auth_change_my_password: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_update_avatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_auth_update_avatar"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    players_list_players: {
        parameters: {
            query?: {
                /** @description Elementos por página */
                limit?: number;
                /** @description Elementos a saltar */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PlayerResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    players_add_player: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    players_get_player: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    players_edit_player: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    players_remove_player: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    players_get_player_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    players_refresh_player: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matches_list_live_matches: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Force full fetch from Riot API */
                live?: boolean;
                /** @description Fetch new matches from Riot until stored history is reached */
                sync?: boolean;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Riot API unavailable and nothing cached */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    matches_list_matches: {
        parameters: {
            query?: {
                /** @description Elementos por página */
                limit?: number;
                /** @description Elementos a saltar */
                offset?: number;
            };
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MatchResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matches_get_stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matches_get_most_played_champions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MostPlayedChampionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_list_snapshots: {
        parameters: {
            query?: {
                /** @description Elementos por página */
                limit?: number;
                /** @description Elementos a saltar */
                offset?: number;
            };
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SnapshotResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_create_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many analyses requested */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Queue unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    snapshots_get_job_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_stream_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eventos `progress`, `done` y `error` con un SnapshotJobStatus en JSON */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_retry_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotJobStatus"];
                };
            };
            /** @description The job has not failed, or an equivalent analysis is running */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_get_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_remove_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_edit_description: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotDescriptionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_edit_notes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SnapshotNotesUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots_read_snapshot_dashboard: {
        parameters: {
            query?: {
                compare_game_name?: string | null;
                compare_tag_line?: string | null;
                compare_region?: string | null;
            };
            header?: never;
            path: {
                snapshot_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotDashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ddragon_get_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    ddragon_get_items: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ddragon_get_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ddragon_get_item_icon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ddragon_get_spells: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ddragon_get_spell: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ddragon_get_runes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    ddragon_get_rune: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rune_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ddragon_get_rune_icon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rune_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ddragon_get_map: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ddragon_get_map_url: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlResponse"];
                };
            };
        };
    };
    league_read_rank_cutoffs: {
        parameters: {
            query: {
                /** @description Player region, e.g. EUW, NA, KR */
                region: string;
                /** @description Force refresh from Riot API */
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankCutoffsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Riot API unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_list_all_players: {
        parameters: {
            query?: {
                /** @description Elementos por página */
                limit?: number;
                /** @description Elementos a saltar */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AdminPlayerOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_admin_delete_player: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_get_global_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GlobalStats"];
                };
            };
        };
    };
    admin_list_users: {
        parameters: {
            query?: {
                /** @description Elementos por página */
                limit?: number;
                /** @description Elementos a saltar */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_update_user_role: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_toggle_user_active: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_delete_inactive_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteInactiveResult"];
                };
            };
        };
    };
    admin_delete_user: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_root: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
}
