"""migracion_inicial_supabase

Revision ID: dba87524cbc7
Revises: 
Create Date: 2026-05-28 19:52:08.386467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba87524cbc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    op.create_table('match_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('creation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('champion', sa.String(length=50), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('kill_participation', sa.Float(), nullable=True),
    sa.Column('vision', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('total_cs', sa.Integer(), nullable=True),
    sa.Column('damage_share', sa.Float(), nullable=True),
    sa.Column('first_dragon', sa.Boolean(), nullable=True),
    sa.Column('void_grubs', sa.Boolean(), nullable=True),
    sa.Column('herald', sa.Boolean(), nullable=True),
    sa.Column('summoner1_id', sa.Integer(), nullable=True),
    sa.Column('summoner2_id', sa.Integer(), nullable=True),
    sa.Column('item0', sa.Integer(), nullable=True),
    sa.Column('item1', sa.Integer(), nullable=True),
    sa.Column('item2', sa.Integer(), nullable=True),
    sa.Column('item3', sa.Integer(), nullable=True),
    sa.Column('item4', sa.Integer(), nullable=True),
    sa.Column('item5', sa.Integer(), nullable=True),
    sa.Column('item6', sa.Integer(), nullable=True),
    sa.Column('primary_rune', sa.Integer(), nullable=True),
    sa.Column('secondary_tree', sa.Integer(), nullable=True),
    sa.Column('death_events', sa.JSON(), nullable=True),
    sa.Column('ward_events', sa.JSON(), nullable=True),
    sa.Column('dragon_setups', sa.JSON(), nullable=True),
    sa.Column('timeline_enriched', sa.Boolean(), nullable=False),
    sa.Column('player_role', sa.String(length=20), nullable=True),
    sa.Column('role_bound_item', sa.Integer(), nullable=False),
    sa.Column('quest_completed', sa.Boolean(), nullable=False),
    sa.Column('quest_completion_time', sa.Integer(), nullable=True),
    sa.Column('enemy_quest_completion_time', sa.Integer(), nullable=True),
    sa.Column('quest_completion_time_diff', sa.Integer(), nullable=True),
    sa.Column('solo_kills', sa.Integer(), nullable=True),
    sa.Column('damage_structures', sa.Integer(), nullable=True),
    sa.Column('gold_share', sa.Float(), nullable=True),
    sa.Column('enemy_jg_monsters', sa.Integer(), nullable=True),
    sa.Column('control_wards', sa.Integer(), nullable=True),
    sa.Column('roaming_proactivity', sa.Integer(), nullable=True),
    sa.Column('objective_vision_score', sa.Integer(), nullable=True),
    sa.Column('early_gank_deaths', sa.Integer(), nullable=True),
    sa.Column('cs_8', sa.Integer(), nullable=True),
    sa.Column('cs_14', sa.Integer(), nullable=True),
    sa.Column('cs_25', sa.Integer(), nullable=True),
    sa.Column('cs_diff_8', sa.Integer(), nullable=True),
    sa.Column('cs_diff_14', sa.Integer(), nullable=True),
    sa.Column('cs_diff_25', sa.Integer(), nullable=True),
    sa.Column('gold_diff_8', sa.Integer(), nullable=True),
    sa.Column('gold_diff_14', sa.Integer(), nullable=True),
    sa.Column('gold_diff_25', sa.Integer(), nullable=True),
    sa.Column('xp_diff_8', sa.Integer(), nullable=True),
    sa.Column('xp_diff_14', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_data_id'), 'match_data', ['id'], unique=False)
    op.create_index(op.f('ix_match_data_match_id'), 'match_data', ['match_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(length=100), nullable=False),
    sa.Column('game_name', sa.String(length=50), nullable=False),
    sa.Column('tag_line', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('TOP', 'JUNGLE', 'MID', 'BOTTOM', 'SUPPORT', 'ALL', name='roleenum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('rank', sa.String(length=5), nullable=True),
    sa.Column('lp', sa.Integer(), nullable=True),
    sa.Column('profile_icon_id', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('match_history_cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'puuid', name='uq_players_user_puuid')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_user_id'), 'players', ['user_id'], unique=False)
    op.create_table('player_match_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'match_id', name='uq_player_match_history')
    )
    op.create_index(op.f('ix_player_match_history_id'), 'player_match_history', ['id'], unique=False)
    op.create_index(op.f('ix_player_match_history_player_id'), 'player_match_history', ['player_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snapshots_id'), 'snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_snapshots_player_id'), 'snapshots', ['player_id'], unique=False)
    op.create_table('match_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'match_id', name='uq_snapshot_match')
    )
    op.create_index(op.f('ix_match_snapshots_id'), 'match_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_match_snapshots_match_id'), 'match_snapshots', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_snapshots_snapshot_id'), 'match_snapshots', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_snapshots_snapshot_id'), table_name='match_snapshots')
    op.drop_index(op.f('ix_match_snapshots_match_id'), table_name='match_snapshots')
    op.drop_index(op.f('ix_match_snapshots_id'), table_name='match_snapshots')
    op.drop_table('match_snapshots')
    op.drop_index(op.f('ix_snapshots_player_id'), table_name='snapshots')
    op.drop_index(op.f('ix_snapshots_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_player_match_history_player_id'), table_name='player_match_history')
    op.drop_index(op.f('ix_player_match_history_id'), table_name='player_match_history')
    op.drop_table('player_match_history')
    op.drop_index(op.f('ix_players_user_id'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_match_data_match_id'), table_name='match_data')
    op.drop_index(op.f('ix_match_data_id'), table_name='match_data')
    op.drop_table('match_data')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
